foldersTree = gFld("<b>OpenTCP</b>", "", "")
     insDoc(foldersTree, gLnk("OpenTCP API documentation", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("/opentcp/arp.c", "", "arp_8c.html"))
       insDoc(aux1, gLnk("/opentcp/ethernet.c", "", "ethernet_8c.html"))
       insDoc(aux1, gLnk("/opentcp/icmp.c", "", "icmp_8c.html"))
       insDoc(aux1, gLnk("/opentcp/ip.c", "", "ip_8c.html"))
       insDoc(aux1, gLnk("/opentcp/system.c", "", "system_8c.html"))
       insDoc(aux1, gLnk("/opentcp/tcp.c", "", "tcp_8c.html"))
       insDoc(aux1, gLnk("/opentcp/timers.c", "", "timers_8c.html"))
       insDoc(aux1, gLnk("/opentcp/udp.c", "", "udp_8c.html"))
       insDoc(aux1, gLnk("/opentcp/arch/mb90f553a/init.c", "", "init_8c.html"))
       insDoc(aux1, gLnk("/opentcp/arch/mb90f553a/vectors.c", "", "vectors_8c.html"))
       insDoc(aux1, gLnk("/opentcp/bootp/bootp.c", "", "bootp_8c.html"))
       insDoc(aux1, gLnk("/opentcp/demo/main_demo.c", "", "main__demo_8c.html"))
       insDoc(aux1, gLnk("/opentcp/demo/tcp_client_demo.c", "", "tcp__client__demo_8c.html"))
       insDoc(aux1, gLnk("/opentcp/demo/tcp_server_demo.c", "", "tcp__server__demo_8c.html"))
       insDoc(aux1, gLnk("/opentcp/demo/udp_demo.c", "", "udp__demo_8c.html"))
       insDoc(aux1, gLnk("/opentcp/dhcp/dhcpc.c", "", "dhcpc_8c.html"))
       insDoc(aux1, gLnk("/opentcp/dns/dns.c", "", "dns_8c.html"))
       insDoc(aux1, gLnk("examples.dxy", "", ""))
       insDoc(aux1, gLnk("groups.dxy", "", ""))
       insDoc(aux1, gLnk("intro.dxy", "", ""))
       insDoc(aux1, gLnk("license.dxy", "", ""))
       insDoc(aux1, gLnk("/opentcp/http/http_server.c", "", "http__server_8c.html"))
       insDoc(aux1, gLnk("/opentcp/http/https_callbacks.c", "", "https__callbacks_8c.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/arp.h", "", "arp_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/datatypes.h", "", "datatypes_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/debug.h", "", "debug_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/ethernet.h", "", "ethernet_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/globalvariables.h", "", "globalvariables_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/ip.h", "", "ip_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/system.h", "", "system_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/tcp_ip.h", "", "tcp__ip_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/timers.h", "", "timers_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/arch/config.h", "", "config_8h.html"))
       insDoc(aux1, gLnk("MB90550.H", "", ""))
       insDoc(aux1, gLnk("/opentcp/include/inet/bootp/bootp.h", "", "bootp_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/dhcp/dhcpc.h", "", "dhcpc_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/dns/dns.h", "", "dns_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/http/http_server.h", "", "http__server_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/pop3/pop3_client.h", "", "pop3__client_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/smtp/smtp_client.h", "", "smtp__client_8h.html"))
       insDoc(aux1, gLnk("/opentcp/include/inet/tftp/tftps.h", "", "tftps_8h.html"))
       insDoc(aux1, gLnk("/opentcp/pop3/pop3_client.c", "", "pop3__client_8c.html"))
       insDoc(aux1, gLnk("/opentcp/pop3/pop3c_callbacks.c", "", "pop3c__callbacks_8c.html"))
       insDoc(aux1, gLnk("/opentcp/smtp/smtp_client.c", "", "smtp__client_8c.html"))
       insDoc(aux1, gLnk("/opentcp/smtp/smtpc_callbacks.c", "", "smtpc__callbacks_8c.html"))
       insDoc(aux1, gLnk("/opentcp/tftp/tftps.c", "", "tftps_8c.html"))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("arp_entry", "", "structarp__entry.html"))
       insDoc(aux1, gLnk("ethernet_frame", "", "structethernet__frame.html"))
       insDoc(aux1, gLnk("http_server_state", "", "structhttp__server__state.html"))
       insDoc(aux1, gLnk("ip_frame", "", "structip__frame.html"))
       insDoc(aux1, gLnk("netif", "", "structnetif.html"))
       insDoc(aux1, gLnk("pop3c_struct", "", "structpop3c__struct.html"))
       insDoc(aux1, gLnk("tcb", "", "structtcb.html"))
       insDoc(aux1, gLnk("tcp_frame", "", "structtcp__frame.html"))
       insDoc(aux1, gLnk("ucb", "", "structucb.html"))
       insDoc(aux1, gLnk("udp_frame", "", "structudp__frame.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("Initialization functions", "", "group__core__initializer.html"))
       insDoc(aux1, gLnk("Main loop functions", "", "group__periodic__functions.html"))
       insDoc(aux1, gLnk("UDP API functions", "", "group__udp__app__api.html"))
       insDoc(aux1, gLnk("TCP API functions", "", "group__tcp__app__api.html"))
       insDoc(aux1, gLnk("OpenTCP examples", "", "group__opentcp__example.html"))
       insDoc(aux1, gLnk("OpenTCP configuration parameters", "", "group__opentcp__config.html"))
aux1 = insFld(foldersTree, gFld("Examples", "", "examples.html"))
       insDoc(aux1, gLnk("main_demo.c", "", "main__demo_8c-example.html"))
       insDoc(aux1, gLnk("tcp_client_demo.c", "", "tcp__client__demo_8c-example.html"))
       insDoc(aux1, gLnk("tcp_server_demo.c", "", "tcp__server__demo_8c-example.html"))
       insDoc(aux1, gLnk("udp_demo.c", "", "udp__demo_8c-example.html"))
     insDoc(foldersTree, gLnk("Globals", "", "globals.html"))
aux1 = insFld(foldersTree, gFld("Related Pages", "", "pages.html"))
       insDoc(aux1, gLnk("OpenTCP License information", "", "license.html"))
       insDoc(aux1, gLnk("Bug List", "", "bug.html"))
       insDoc(aux1, gLnk("Todo List", "", "todo.html"))
